version: '3.9'

services:
  text_to_speech:
    image: text_to_speech:030715
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: text_to_speech
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - voice-storage:/app/Voice
      - output-storage:/app/output
    restart: always
    networks:
      - ai-network
    environment:
      - PYTHONUNBUFFERED=1
      - COQUI_TOS_AGREED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ai-network: 
    driver: bridge

volumes:
  voice-storage:
  output-storage: