version: '3.9'

services:
  multi_language_translation:
    image: multi_language_translation:030715
    build: 
      context: multi_language_translation
    container_name: multi_language_translation
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    networks:
      - ai-network

  speech_to_text:
    image: speech_to_text:030715
    build: 
      context: speech_to_text
    container_name: speech_to_text
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    restart: always
    networks:
      - ai-network

  text_to_speech:
    image: text_to_speech:030715
    build: 
      context: text_to_speech
    container_name: text_to_speech
    ports:
      - "8002:8002"
    volumes:
      - .:/app
      - voice-storage:/app/Voice
      - output-storage:/app/output
    restart: always
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge

volumes:
  voice-storage:
  output-storage:
