version: "3.9"

services:
  app:
    build: .
    container_name: tts-stt
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - COQUI_TOS_AGREED=1
    restart: unless-stopped
