version: '3.9'

services:
  speech_to_text:
    image: speech_to_text:030715
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: speech_to_text
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    restart: always
    networks:
      - ai-network
networks:
  ai-network:
    driver: bridge